name: my_portfolio
description: A my portfolio app.
publish_to: "none"
version: 1.1.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.3.1 #don't support web
  connectivity_plus: ^6.0.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  http: ^1.2.1
  image_network: ^2.5.6 # for web only
  # internet_connection_checker: ^1.0.0+1 #don't support web
  lottie: ^3.1.0 #don't support web
  # rename: ^3.0.2 #don't support web
  responsive_sizer: ^3.3.0+1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

dev_dependencies:
  build_runner: ^2.4.8 #don't support web
  # change_app_package_name: ^1.1.0 #don't support web
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  # icons_launcher: ^2.1.7  #don't support web
  mockito: ^5.4.4
# rename setAppName --targets ios,android --value "amadytech"
# rename setBundleId --targets ios,android --value "com.amadytech.amadytech"
# flutter pub run change_app_package_name:main com.amadytech.amadytech
# flutter pub get
# dart run icons_launcher:create
# icons_launcher:
#   image_path: "assets/images/ic_launcher.png"
#   platforms:
#     android:
#       enable: true
#     ios:
#       enable: true
#     web:
#       enable: true
#     macos:
#       enable: true
#     windows:
#       enable: true
#     linux:
#       enable: true

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/ic_launcher.png"
  background_image: "assets/images/background_ic_launcher.png"
  branding: "assets/images/background_ic_launcher.png"
  color_dark: "#121212"
  # color_dark: "#ffffff"
  image_dark: "assets/images/ic_launcher.png"
  branding_dark: "assets/images/background_ic_launcher.png"
  android_12:
    image: "assets/images/ic_launcher.png"
    icon_background_color: "#ffffff"
    image_dark: "assets/images/ic_launcher.png"
    icon_background_color_dark: "#121212"
  android_gravity: center
  web_image_mode: center
  ios_content_mode: center
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
